### PR TITLE
Dev mode

### PR DESCRIPTION
**Pull request by evelinec**
**Required changes:**
- use the ideal(simplified) pom.xml
- update the Readme content to use dev mode
  - keep the flow same 
- convert `*Test` class to `*IT` 
- convert to use JUnit 5
  - use JUnit5 test order if need
- make sure to correctly configure the ports in test classes, server.xml, and pom.xml
- update travis test
   - `mvn install` cannot be used to verify anymore

Also added SEO title and description.

### CODE REVIEW

**Comment by evelinec** [comment]
This peer review checklist may be used:

- [ ] Check that the guide has working instructions and sample code
- [ ] Check the quality of code according to the best coding practices
- [ ] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [ ] Check that all licensing statements are properly stated in all files
- [ ] Check that the `pom.xml`, `server.xml`, etc files are clean
- [ ] Test the guide on 3 platforms: Mac, Win, Linux
- [ ] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides
- [ ] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

**Comment by ankitagrawa** [comment]
Should we give instructions at the end on how to quit the dev mode?

**Comment by evelinec** [comment]
> Should we give instructions at the end on how to quit the dev mode?

Fixed. Pls refresh the lgdev site. Thanks.

**Comment by evelinec** [comment]
Merged into qa branch, and refreshing qa site for further verification.

**Pull request merged**
